<?php

use App\Http\Controllers\dashboardController;
use App\Http\Controllers\PaymentsExportController;
use App\Http\Controllers\StudentListController;
use App\Services\ClassAllocationServices\ClassAllocationServices;
use App\Services\CoursesServices\CoursesServices;
use App\Services\ProgrammesServices\ProgrammesServices;
use App\Services\StaffServices\StaffServices;
use Illuminate\Http\Request as HttpRequest;
use App\Http\Controllers\ResultProcessingController;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\ScoresUploadController;
use App\Http\Controllers\StatementOfResultController;
use App\Http\Controllers\TFAController;
use App\Http\Controllers\ScoresBreakDownController;
use App\Http\Controllers\SpecialGradesController;
use App\Models\Student;
use Symfony\Component\HttpKernel\HttpKernel;
use App\Http\Controllers\PracticalsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/2FA', [TFAController::class, 'get2FA']);
Route::POST('/2FA', [TFAController::class, 'submit2FA'])->name('TFA');
Auth::routes();
Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return redirect('/dashboard');
    });
    Route::get('/role/{id}/addPermission', [App\Http\Controllers\RolesController::class, 'addPermission']);

    Route::resource('/courses', CourseController::class);
    Route::resource('/roles',  RolesController::class);
    Route::resource('/permissions',    PermissionsController::class);
    Route::get('/scoresBreakDown', [ScoresBreakDownController::class, 'index']);
    Route::get('/scoresBreakDown/{id}', [ScoresBreakDownController::class, 'show']);
    Route::delete('/scoresBreakDown/{id}/destroy', [ScoresBreakDownController::class, 'destroy']);
    Route::patch('/scoresBreakDown', [ScoresBreakDownController::class, 'update']);

    Route::get('/practicals', function () {
        session()->put('scoreType', 'practicals');
        return view('scoresUpload.practical');
    });
    Route::get('/statementOfResult', function () {
        return view('results.SORView');
    });
    Route::post('/capturePracticalsScores', [PracticalsController::class, 'captureScores']);
    Route::get('/getPracticalsConducted', [PracticalsController::class, 'getPracticalsConducted']);
    Route::POST('/statementOfResult', [StatementOfResultController::class, 'index']);

    Route::get('/uploadScores/{type}', [ScoresUploadController::class, 'index']);
    Route::post('/uploadScores', [ScoresUploadController::class, 'upload']);
    Route::get('/dashboard', [dashboardController::class, 'index'])->name('dashboard');

    Route::get('/downloadStudentList', [StudentListController::class, 'index'])->name('studentsListView');
    Route::post('/downloadStudentList', [StudentListController::class, 'download'])->name('downloadStudentsList');
    Route::resource('/classAllocation', ClassAllocationController::class);

    Route::get('/processResults', [ResultProcessingController::class, 'index']);
    Route::post('/processResults', [ResultProcessingController::class, 'process']);

    Route::get('/specialCases', [SpecialGradesController::class, 'index']);
    Route::post('/studentSpecialCase', [SpecialGradesController::class, 'studentCase']);
    Route::post('/classSpecialCase', [SpecialGradesController::class, 'classCase']);

    //api calls
    Route::get('/getStaffByFileNo', function (HttpRequest $request) {
        return StaffServices::getStaffByFileNo($request->file_no);
    });
    Route::get('/getStudentByRegNo', function (HttpRequest $request) {
        return Student::with(['programme', 'department', 'programme.course'])->where('REG_NUMBER', $request->reg_no)->first();
    });

    Route::get('/getProgrammesByDeptAndType', function (HttpRequest $request) {
        return ProgrammesServices::getProgrammesByDeptAndType($request->dept_id, $request->programme_type);
    });

    Route::get('/getCoursesForScoresLimit', function (HttpRequest $request) {
        return CoursesServices::getCourseByCodeLike($request->code);
    });
    Route::get('/getCADepts', function (HttpRequest $request) {
        return ClassAllocationServices::getDept($request->programme_type);
    });
    Route::get('/getCAProgs', function (HttpRequest $request) {
        return ClassAllocationServices::getProgramme($request->programme_type, $request->dept_id);
    });
    Route::get('/getCASessions', function (HttpRequest $request) {
        return ClassAllocationServices::getSession($request->programme_type, $request->dept_id, $request->prog_id);
    });
    Route::get('/getCASemesters', function (HttpRequest $request) {
        return ClassAllocationServices::getSemester($request->programme_type, $request->dept_id, $request->prog_id, $request->session);
    });
    Route::get('/getCACourses', function (HttpRequest $request) {
        return ClassAllocationServices::getCourses($request->programme_type, $request->dept_id, $request->prog_id, $request->session, $request->semester);
    });
    Route::get('/getProgrammesByProgrammeType', function (HttpRequest $request) {
        return ProgrammesServices::getProgrammesByDeptAndType(auth()->user()->staff->dept_id, $request->programme_type);
    });
    Route::get('/getCoursesByProgID', function (HttpRequest $request) {
        return CoursesServices::getCoursesByProgID($request->prog_id);
    });
});

Route::prefix('icon')->group(function () {  // word: "icons" - not working as part of adress
    Route::get('/coreui-icons', function () {
        return view('dashboard.icons.coreui-icons');
    });
    Route::get('/flags', function () {
        return view('dashboard.icons.flags');
    });
    Route::get('/brands', function () {
        return view('dashboard.icons.brands');
    });
});

Route::get('/getPayments', [PaymentsExportController::class, 'index']);


Route::get('/test', function () {
    //dd(Str::ucfirst(strtolower("THIS IS A SAMPLE")));
    $headers = [
        'id', 'option_en', 'option_es', 'option_cat', 'option_val'
    ];
    /*$headers = [
        'id', 'case_title_en', 'case_title_es', 'case_title_cat', 'case_title_val', 'icon', 'description', 'case_sno'
    ];
    */
    $data = DB::table('lifestyle_options')->select()->get();
    $q = "";
    foreach ($data as $d) {
        $q .= '[';
        foreach ($headers as $h) {
            $q .= '"' . $h . '"=>"' . trim($d->$h) . '" ,';
        }
        $q = substr($q, 0, strlen($q) - 1);
        $q .= "] , \n";
    }
    return $q;
    $q = substr($q, 0, strlen($q) - 1);

    dd($q, $data, $headers);
});



/*

$data = [
    ["id" => "1", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk in place, normal pace", "idMET" => "17250", "MET" => "3.50", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar en el sitio, paso normal", "description_es" => "caminar en el sitio, paso normal", "description_val" => "caminar en el sitio, paso normal", "exercise_type_val" => "caminar en el sitio", "exercise_type_es" => "caminar en el sitio", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar en el sitio", "exercise_level_val" => "paso normal", "exercise_level_es" => "paso normal", "exercise_level_en" => "in place normal pace", "exercise_level_cat" => "paso normal"],
    ["id" => "2", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk on site, brisk pace", "idMET" => "17200", "MET" => "4.30", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar en el sitio, paso rápido", "description_es" => "caminar en el sitio, paso rápido", "description_val" => "caminar en el sitio, paso rápido", "exercise_type_val" => "caminar en el sitio", "exercise_type_es" => "caminar en el sitio", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar en el sitio", "exercise_level_val" => "paso rápido", "exercise_level_es" => "paso rápido", "exercise_level_en" => "on site brisk pace", "exercise_level_cat" => "paso rápido"],
    ["id" => "3", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk in place, slow pace", "idMET" => "17152", "MET" => "1.00", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar en el sitio, paso lento", "description_es" => "caminar en el sitio, paso lento", "description_val" => "caminar en el sitio, paso lento", "exercise_type_val" => "caminar en el sitio", "exercise_type_es" => "caminar en el sitio", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar en el sitio", "exercise_level_val" => "paso lento", "exercise_level_es" => "paso lento", "exercise_level_en" => "in place slow pace", "exercise_level_cat" => "paso lento"],
    ["id" => "4", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, normal pace", "idMET" => "17250", "MET" => "3.50", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, paso normal", "description_es" => "caminar, paso normal", "description_val" => "caminar, paso normal", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "paso normal", "exercise_level_es" => "paso normal", "exercise_level_en" => "normal pace", "exercise_level_cat" => "paso normal"],
    ["id" => "5", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, fast pace", "idMET" => "17200", "MET" => "4.30", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, paso rápido", "description_es" => "caminar, paso rápido", "description_val" => "caminar, paso rápido", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "paso rápido", "exercise_level_es" => "paso rápido", "exercise_level_en" => "fast pace", "exercise_level_cat" => "paso rápido"],
    ["id" => "6", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, slow pace", "idMET" => "17152", "MET" => "2.80", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, paso lento", "description_es" => "caminar, paso lento", "description_val" => "caminar, paso lento", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "paso lento", "exercise_level_es" => "paso lento", "exercise_level_en" => "slow pace", "exercise_level_cat" => "paso lento"],
    ["id" => "7", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, moderate speed", "idMET" => "17088", "MET" => "4.50", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "marcha, velocidad moderada", "description_es" => "marcha, velocidad moderada", "description_val" => "marcha, velocidad moderada", "exercise_type_val" => "marcha", "exercise_type_es" => "marcha", "exercise_type_en" => "climb", "exercise_type_cat" => "marcha", "exercise_level_val" => "velocidad moderada", "exercise_level_es" => "velocidad moderada", "exercise_level_en" => "moderate speed", "exercise_level_cat" => "velocidad moderada"],
    ["id" => "8", "video_yt_name" => "IMG_0001", "routine_en" => "Session", "description_en" => "Functional Advanced 1", "idMET" => "2020", "MET" => "8.00", "duration" => "29", "youtube" => "https://youtube.com/embed/VVxyqEE0kkQ", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional avanzado 1", "description_es" => "Funcional avanzado 1", "description_val" => "Funcional avanzado 1", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Funcional", "exercise_level_val" => "avanzado 1", "exercise_level_es" => "avanzado 1", "exercise_level_en" => "Advanced 1", "exercise_level_cat" => "avanzado 1"],
    ["id" => "9", "video_yt_name" => "IMG_4736", "routine_en" => "Session", "description_en" => "Pilates Basic 1", "idMET" => "2105", "MET" => "3.00", "duration" => "21", "youtube" => "https://youtube.com/embed/l3Cf1zAv5zg", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates básico (1)", "description_es" => "Pilates básico (1)", "description_val" => "Pilates básico (1)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Pilates", "exercise_level_val" => "básico -1", "exercise_level_es" => "básico -1", "exercise_level_en" => "Basic 1", "exercise_level_cat" => "básico -1"],
    ["id" => "10", "video_yt_name" => "IMG_4737", "routine_en" => "Session", "description_en" => "Pilates Basic 2", "idMET" => "2105", "MET" => "3.00", "duration" => "21", "youtube" => "https://youtube.com/embed/WKP1QFi892k", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates básico (2)", "description_es" => "Pilates básico (2)", "description_val" => "Pilates básico (2)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Calentamiento", "exercise_type_cat" => "Pilates", "exercise_level_val" => "básico -2", "exercise_level_es" => "básico -2", "exercise_level_en" => "Basic 2", "exercise_level_cat" => "básico -2"],
    ["id" => "11", "video_yt_name" => "IMG_4738", "routine_en" => "Session", "description_en" => "Calentamiento Functional 1", "idMET" => "2101", "MET" => "2.30", "duration" => "9", "youtube" => "https://youtube.com/embed/HoNfIJYbLeQ", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Calentamiento funcional (1)", "description_es" => "Calentamiento funcional (1)", "description_val" => "Calentamiento funcional (1)", "exercise_type_val" => "Calentamiento", "exercise_type_es" => "Calentamiento", "exercise_type_en" => "Calentamiento", "exercise_type_cat" => "Calentamiento", "exercise_level_val" => "funcional -1", "exercise_level_es" => "funcional -1", "exercise_level_en" => "Functional 1", "exercise_level_cat" => "funcional -1"],
    ["id" => "12", "video_yt_name" => "IMG_4742", "routine_en" => "Session", "description_en" => "Calentamiento Functional 2", "idMET" => "2101", "MET" => "2.30", "duration" => "9", "youtube" => "https://youtube.com/embed/omAkERO5QS0", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Calentamiento funcional (2)", "description_es" => "Calentamiento funcional (2)", "description_val" => "Calentamiento funcional (2)", "exercise_type_val" => "Calentamiento", "exercise_type_es" => "Calentamiento", "exercise_type_en" => "Functional", "exercise_type_cat" => "Calentamiento", "exercise_level_val" => "funcional -2", "exercise_level_es" => "funcional -2", "exercise_level_en" => "Functional 2", "exercise_level_cat" => "funcional -2"],
    ["id" => "13", "video_yt_name" => "IMG_4756", "routine_en" => "Session", "description_en" => "Functional basic 1", "idMET" => "2024", "MET" => "2.80", "duration" => "7", "youtube" => "https://youtube.com/embed/v9voB7DfCK0", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional básico (1)", "description_es" => "Funcional básico (1)", "description_val" => "Funcional básico (1)", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "básico -1", "exercise_level_es" => "básico -1", "exercise_level_en" => "basic 1", "exercise_level_cat" => "básico -1"],
    ["id" => "14", "video_yt_name" => "IMG_4758", "routine_en" => "Session", "description_en" => "Functional basic 2", "idMET" => "2024", "MET" => "2.80", "duration" => "9", "youtube" => "https://youtube.com/embed/Yhh0Ki4dz94", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional básico (2)", "description_es" => "Funcional básico (2)", "description_val" => "Funcional básico (2)", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Funcional", "exercise_level_val" => "básico -2", "exercise_level_es" => "básico -2", "exercise_level_en" => "basic 2", "exercise_level_cat" => "básico -2"],
    ["id" => "15", "video_yt_name" => "IMG_4777", "routine_en" => "Session", "description_en" => "Pilates medium 1", "idMET" => "2105", "MET" => "3.00", "duration" => "29", "youtube" => "https://youtube.com/embed/eH4Er_DrP9g", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates medio (1)", "description_es" => "Pilates medio (1)", "description_val" => "Pilates medio (1)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Pilates", "exercise_level_val" => "medio -1", "exercise_level_es" => "medio -1", "exercise_level_en" => "medium 1", "exercise_level_cat" => "medio -1"],
    ["id" => "16", "video_yt_name" => "IMG_4781", "routine_en" => "Session", "description_en" => "Pilates medium 2", "idMET" => "2105", "MET" => "3.00", "duration" => "26", "youtube" => "https://youtube.com/embed/hT68nvQqHOs", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates medio (2)", "description_es" => "Pilates medio (2)", "description_val" => "Pilates medio (2)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Functional", "exercise_type_cat" => "Pilates", "exercise_level_val" => "medio -2", "exercise_level_es" => "medio -2", "exercise_level_en" => "medium 2", "exercise_level_cat" => "medio -2"],
    ["id" => "17", "video_yt_name" => "IMG_4786", "routine_en" => "Session", "description_en" => "Functional medium 1", "idMET" => "2022", "MET" => "3.80", "duration" => "24", "youtube" => "https://youtube.com/embed/qpEO_CJuph4", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional medio (1)", "description_es" => "Funcional medio (1)", "description_val" => "Funcional medio (1)", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Funcional", "exercise_level_val" => "medio -1", "exercise_level_es" => "medio -1", "exercise_level_en" => "medium 1", "exercise_level_cat" => "medio -1"],



    ["id" => "18", "video_yt_name" => "IMG_4796", "routine_en" => "Session", "description_en" => "Pilates Advanced 1", "idMET" => "2105", "MET" => "3.00", "duration" => "40", "youtube" => "https://youtube.com/embed/kAkyr3BrzPw", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates avanzado (1)", "description_es" => "Pilates avanzado (1)", "description_val" => "Pilates avanzado (1)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Pilates", "exercise_type_cat" => "Pilates", "exercise_level_val" => "avanzado -1", "exercise_level_es" => "avanzado -1", "exercise_level_en" => "Advanced 1", "exercise_level_cat" => "avanzado -1"],
    ["id" => "19", "video_yt_name" => "IMG_4797", "routine_en" => "Session", "description_en" => "Pilates Advanced 2", "idMET" => "2105", "MET" => "3.00", "duration" => "40", "youtube" => "https://youtube.com/embed/HGRPSUnOivk", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Pilates avanzado (2)", "description_es" => "Pilates avanzado (2)", "description_val" => "Pilates avanzado (2)", "exercise_type_val" => "Pilates", "exercise_type_es" => "Pilates", "exercise_type_en" => "Functional", "exercise_type_cat" => "Pilates", "exercise_level_val" => "avanzado -2", "exercise_level_es" => "avanzado -2", "exercise_level_en" => "Advanced 2", "exercise_level_cat" => "avanzado -2"],
    ["id" => "20", "video_yt_name" => "IMG_4815", "routine_en" => "Session", "description_en" => "Functional medium 2", "idMET" => "2022", "MET" => "3.80", "duration" => "16", "youtube" => "https://youtube.com/embed/Bsh3zbgYtps", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional medio (2)", "description_es" => "Funcional medio (2)", "description_val" => "Funcional medio (2)", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Yoga", "exercise_type_cat" => "Funcional", "exercise_level_val" => "medio -2", "exercise_level_es" => "medio -2", "exercise_level_en" => "medium 2", "exercise_level_cat" => "medio -2"],
    ["id" => "21", "video_yt_name" => "IMG_4815 2", "routine_en" => "Session", "description_en" => "Yoga basic 1", "idMET" => "2170", "MET" => "2.00", "duration" => "15", "youtube" => "https://youtube.com/embed/HQ7kjG-Jmrc", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Yoga básico (1)", "description_es" => "Yoga básico (1)", "description_val" => "Yoga básico (1)", "exercise_type_val" => "Yoga", "exercise_type_es" => "Yoga", "exercise_type_en" => "Yoga", "exercise_type_cat" => "Yoga", "exercise_level_val" => "básico -1", "exercise_level_es" => "básico -1", "exercise_level_en" => "basic 1", "exercise_level_cat" => "básico -1"],
    ["id" => "22", "video_yt_name" => "IMG_4816 2", "routine_en" => "Session", "description_en" => "Yoga basic 2", "idMET" => "2170", "MET" => "2.00", "duration" => "20", "youtube" => "https://youtube.com/embed/NVNbXa6BDVM", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Yoga básico (2)", "description_es" => "Yoga básico (2)", "description_val" => "Yoga básico (2)", "exercise_type_val" => "Yoga", "exercise_type_es" => "Yoga", "exercise_type_en" => "Yoga", "exercise_type_cat" => "Yoga", "exercise_level_val" => "básico -2", "exercise_level_es" => "básico -2", "exercise_level_en" => "basic 2", "exercise_level_cat" => "básico -2"],
    ["id" => "23", "video_yt_name" => "IMG_4817 2", "routine_en" => "Session", "description_en" => "Yoga basic 3", "idMET" => "2170", "MET" => "2.00", "duration" => "17", "youtube" => "https://youtube.com/embed/JDndIS9_v7Q", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Yoga básico (3)", "description_es" => "Yoga básico (3)", "description_val" => "Yoga básico (3)", "exercise_type_val" => "Yoga", "exercise_type_es" => "Yoga", "exercise_type_en" => "Functional", "exercise_type_cat" => "Yoga", "exercise_level_val" => "básico -3", "exercise_level_es" => "básico -3", "exercise_level_en" => "basic 3", "exercise_level_cat" => "básico -3"],
    ["id" => "24", "video_yt_name" => "IMG_5143", "routine_en" => "Session", "description_en" => "Functional Advanced 2", "idMET" => "2020", "MET" => "8.00", "duration" => "29", "youtube" => "https://youtube.com/embed/43pfYOKwooU", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional avanzado (2)", "description_es" => "Funcional avanzado (2)", "description_val" => "Funcional avanzado (2)", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "", "exercise_type_cat" => "Funcional", "exercise_level_val" => "avanzado -2", "exercise_level_es" => "avanzado -2", "exercise_level_en" => "Advanced 2", "exercise_level_cat" => "avanzado -2"],
    ["id" => "25", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, general", "idMET" => "2010", "MET" => "7.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, general", "description_es" => "ciclismo, estacionario, general", "description_val" => "ciclismo, estacionario, general", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario general", "exercise_level_es" => "estacionario general", "exercise_level_en" => "Stationary general", "exercise_level_cat" => "estacionario general"],
    ["id" => "26", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "Elliptical trainer, moderate effort", "idMET" => "2048", "MET" => "5.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "Bicicleta elíptica, esfuerzo moderado", "description_es" => "Bicicleta elíptica, esfuerzo moderado", "description_val" => "Bicicleta elíptica, esfuerzo moderado", "exercise_type_val" => "Bicicleta elíptica", "exercise_type_es" => "Bicicleta elíptica", "exercise_type_en" => "cycling", "exercise_type_cat" => "Bicicleta elíptica", "exercise_level_val" => "esfuerzo moderado", "exercise_level_es" => "esfuerzo moderado", "exercise_level_en" => "trainer moderate effort", "exercise_level_cat" => "esfuerzo moderado"],
    ["id" => "27", "video_yt_name" => "", "routine_en" => "Exercise", "description_en" => "saltar la cuerda, general", "idMET" => "2068", "MET" => "12.30", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ejercicio", "routine_cat" => "Exercici", "routine_val" => "Exercici", "description_cat" => "saltar la cuerda, general", "description_es" => "saltar la cuerda, general", "description_val" => "saltar la cuerda, general", "exercise_type_val" => "saltar la cuerda", "exercise_type_es" => "saltar la cuerda", "exercise_type_en" => "Functional", "exercise_type_cat" => "saltar la cuerda", "exercise_level_val" => "general", "exercise_level_es" => "general", "exercise_level_en" => "la cuerda general", "exercise_level_cat" => "general"],
    ["id" => "28", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run, general", "idMET" => "12020", "MET" => "7.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr, general", "description_es" => "correr, general", "description_val" => "correr, general", "exercise_type_val" => "correr", "exercise_type_es" => "correr", "exercise_type_en" => "run", "exercise_type_cat" => "correr", "exercise_level_val" => "general", "exercise_level_es" => "general", "exercise_level_en" => "general", "exercise_level_cat" => "general"],
    ["id" => "29", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run on site", "idMET" => "12025", "MET" => "8.00", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr en el sitio", "description_es" => "correr en el sitio", "description_val" => "correr en el sitio", "exercise_type_val" => "correr en el sitio", "exercise_type_es" => "correr en el sitio", "exercise_type_en" => "run", "exercise_type_cat" => "correr en el sitio", "exercise_level_val" => "", "exercise_level_es" => "", "exercise_level_en" => "on site", "exercise_level_cat" => ""],
    ["id" => "30", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, less than 3.22 km / h, level, stroll, very slow", "idMET" => "17151", "MET" => "2.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, menos de 3,22 km / h, nivel, pasear, muy lento", "description_es" => "caminar, menos de 3,22 km / h, nivel, pasear, muy lento", "description_val" => "caminar, menos de 3,22 km / h, nivel, pasear, muy lento", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "menos de 3 22 km / h nivel pasear muy lento", "exercise_level_es" => "menos de 3 22 km / h nivel pasear muy lento", "exercise_level_en" => "less than 3.22 km / h level stroll", "exercise_level_cat" => "menos de 3 22 km / h nivel pasear muy lento"],
    ["id" => "31", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 3.22 km / h, level, slow pace, firm surface", "idMET" => "17100", "MET" => "2.80", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminando, 3,22 km / h, nivelado, paso lento, superficie firme", "description_es" => "caminando, 3,22 km / h, nivelado, paso lento, superficie firme", "description_val" => "caminando, 3,22 km / h, nivelado, paso lento, superficie firme", "exercise_type_val" => "caminando", "exercise_type_es" => "caminando", "exercise_type_en" => "walk", "exercise_type_cat" => "caminando", "exercise_level_val" => "3 22 km / h nivelado paso lento superficie firme", "exercise_level_es" => "3 22 km / h nivelado paso lento superficie firme", "exercise_level_en" => "3.22 Km / h level slow pace, firm surface", "exercise_level_cat" => "3 22 km / h nivelado paso lento superficie firme"],
    ["id" => "32", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, 4.0 km / h, level, firm surface", "idMET" => "17170", "MET" => "3.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 4,0 km / h, nivelado, superficie firme", "description_es" => "caminar, 4,0 km / h, nivelado, superficie firme", "description_val" => "caminar, 4,0 km / h, nivelado, superficie firme", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "4 0 km / h nivelado superficie firme", "exercise_level_es" => "4 0 km / h nivelado superficie firme", "exercise_level_en" => "4 km / h level firm surface", "exercise_level_cat" => "4 0 km / h nivelado superficie firme"],
    ["id" => "33", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, 4.0 km / h, downhill", "idMET" => "17180", "MET" => "3.30", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 4,0 km / h, cuesta abajo", "description_es" => "caminar, 4,0 km / h, cuesta abajo", "description_val" => "caminar, 4,0 km / h, cuesta abajo", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "4 0 km / h cuesta abajo", "exercise_level_es" => "4 0 km / h cuesta abajo", "exercise_level_en" => "4 km / h downhill", "exercise_level_cat" => "4 0 km / h cuesta abajo"],
    ["id" => "34", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 4.5 to 5.2 km / h, level, moderate pace, firm surface", "idMET" => "17190", "MET" => "3.50", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 4,5 a 5.2 km / h, nivelado, paso moderado, superficie firme", "description_es" => "caminar, 4,5 a 5.2 km / h, nivelado, paso moderado, superficie firme", "description_val" => "caminar, 4,5 a 5.2 km / h, nivelado, paso moderado, superficie firme", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "4 5 a 5.2 km / h nivelado paso moderado superficie firme", "exercise_level_es" => "4 5 a 5.2 km / h nivelado paso moderado superficie firme", "exercise_level_en" => "4.5 to 5.2 km / h level moderate", "exercise_level_cat" => "4 5 a 5.2 km / h nivelado paso moderado superficie firme"],
    ["id" => "35", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 3.5 mph, level, brisk, firm surface, walking for exercise", "idMET" => "17200", "MET" => "4.30", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 5,6 km / h, nivelado, enérgico, superficie firme, caminar para hacer ejercicio", "description_es" => "caminar, 5,6 km / h, nivelado, enérgico, superficie firme, caminar para hacer ejercicio", "description_val" => "caminar, 5,6 km / h, nivelado, enérgico, superficie firme, caminar para hacer ejercicio", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "5 6 km / h nivelado enérgico superficie firme caminar para hacer ejercicio", "exercise_level_es" => "5 6 km / h nivelado enérgico superficie firme caminar para hacer ejercicio", "exercise_level_en" => "3.5 mph level brisk firm surface", "exercise_level_cat" => "5 6 km / h nivelado enérgico superficie firme caminar para hacer ejercicio"],
    ["id" => "36", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 4.7 to 5.6 km / h, uphill, 1 to 5% grade", "idMET" => "17210", "MET" => "5.30", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 1 a 5% de pendiente", "description_es" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 1 a 5% de pendiente", "description_val" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 1 a 5% de pendiente", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "4 7 a 5 6 km / h cuesta arriba 1 a 5% de pendiente", "exercise_level_es" => "4 7 a 5 6 km / h cuesta arriba 1 a 5% de pendiente", "exercise_level_en" => "4.7 to 5.6 km / h uphill 1", "exercise_level_cat" => "4 7 a 5 6 km / h cuesta arriba 1 a 5% de pendiente"],
    [
        "id" => "37", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 4.7 to 5.6 km / h, uphill, 6 to 15% grade", "idMET" => "17211", "MET" => "8.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 6 a 15% de pendiente", "description_es" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 6 a 15% de pendiente", "description_val" => "caminar, 4,7 a 5,6 km / h, cuesta arriba, 6 a 15% de pendiente", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "4 7 a 5 6 km / h cuesta arriba 6 a 15% de pendiente", "exercise_level_es" => "4 7 a 5 6 km / h cuesta arriba 6 a 15% de pendiente", "exercise_level_en" => "4.7 to 5.6 km / h uphill 6", "exercise_level_cat" => "4 7 a 5 6 km / h cuesta arriba 6 a 15% de pendiente"
    ],
    ["id" => "38", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 6.4 km / h, level, firm surface, very fast pace", "idMET" => "17220", "MET" => "5.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 6,4 km / h, nivelado, superficie firme, paso muy rápido", "description_es" => "caminar, 6,4 km / h, nivelado, superficie firme, paso muy rápido", "description_val" => "caminar, 6,4 km / h, nivelado, superficie firme, paso muy rápido", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "6 4 km / h nivelado superficie firme paso muy rápido", "exercise_level_es" => "6 4 km / h nivelado superficie firme paso muy rápido", "exercise_level_en" => "6.4 km / h level firm surface very", "exercise_level_cat" => "6 4 km / h nivelado superficie firme paso muy rápido"],
    ["id" => "39", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking, 7.2 km / h, level, firm surface, very, very fast", "idMET" => "17230", "MET" => "7.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 7,2 km / h, nivelado, superficie firme, muy, muy rápido", "description_es" => "caminar, 7,2 km / h, nivelado, superficie firme, muy, muy rápido", "description_val" => "caminar, 7,2 km / h, nivelado, superficie firme, muy, muy rápido", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "7 2 km / h nivelado superficie firme muy muy rápido", "exercise_level_es" => "7 2 km / h nivelado superficie firme muy muy rápido", "exercise_level_en" => "7.2 km / h level firm surface very", "exercise_level_cat" => "7 2 km / h nivelado superficie firme muy muy rápido"],
    ["id" => "40", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, 8 km / h, level, firm surface", "idMET" => "17231", "MET" => "8.30", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 8 km / h, nivelado, superficie firme", "description_es" => "caminar, 8 km / h, nivelado, superficie firme", "description_val" => "caminar, 8 km / h, nivelado, superficie firme", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "8 km / h nivelado superficie firme", "exercise_level_es" => "8 km / h nivelado superficie firme", "exercise_level_en" => "8 km / h level firm surface", "exercise_level_cat" => "8 km / h nivelado superficie firme"],
    ["id" => "41", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, 8 km / h, uphill, 3% slope", "idMET" => "17235", "MET" => "9.80", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, 8 km / h, cuesta arriba, pendiente del 3%", "description_es" => "caminar, 8 km / h, cuesta arriba, pendiente del 3%", "description_val" => "caminar, 8 km / h, cuesta arriba, pendiente del 3%", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "8 km / h cuesta arriba pendiente del 3%", "exercise_level_es" => "8 km / h cuesta arriba pendiente del 3%", "exercise_level_en" => "8 km / h uphill 0.03 slope", "exercise_level_cat" => "8 km / h cuesta arriba pendiente del 3%"],
    ["id" => "42", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, grass track", "idMET" => "17260", "MET" => "4.80", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, pista de hierba", "description_es" => "caminar, pista de hierba", "description_val" => "caminar, pista de hierba", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walking", "exercise_type_cat" => "caminar", "exercise_level_val" => "pista de hierba", "exercise_level_es" => "pista de hierba", "exercise_level_en" => "grass track", "exercise_level_cat" => "pista de hierba"],
    ["id" => "43", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walk, normal pace, plowed field or sand", "idMET" => "17262", "MET" => "4.50", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "caminar, paso normal, campo arado o arena", "description_es" => "caminar, paso normal, campo arado o arena", "description_val" => "caminar, paso normal, campo arado o arena", "exercise_type_val" => "caminar", "exercise_type_es" => "caminar", "exercise_type_en" => "walk", "exercise_type_cat" => "caminar", "exercise_level_val" => "paso normal campo arado o arena", "exercise_level_es" => "paso normal campo arado o arena", "exercise_level_en" => "normal pace plowed field or sand", "exercise_level_cat" => "paso normal campo arado o arena"],
    ["id" => "44", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, general", "idMET" => "1015", "MET" => "7.50", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, general", "description_es" => "ciclismo, general", "description_val" => "ciclismo, general", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "general", "exercise_level_es" => "general", "exercise_level_en" => "general", "exercise_level_cat" => "general"],
    ["id" => "45", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, ocio, 8,9 km / h", "idMET" => "1018", "MET" => "3.50", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, ocio, 8,9 km / h", "description_es" => "ciclismo, ocio, 8,9 km / h", "description_val" => "ciclismo, ocio, 8,9 km / h", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "saltar", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "ocio 8 9 km / h", "exercise_level_es" => "ocio 8 9 km / h", "exercise_level_en" => "ocio 8 9 km / h", "exercise_level_cat" => "ocio 8 9 km / h"],
    ["id" => "46", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, ocio, 15,2 km / h", "idMET" => "1019", "MET" => "5.80", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, ocio, 15,2 km / h", "description_es" => "ciclismo, ocio, 15,2 km / h", "description_val" => "ciclismo, ocio, 15,2 km / h", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "ocio 15 2 km / h", "exercise_level_es" => "ocio 15 2 km / h", "exercise_level_en" => "ocio 15 2 km / h", "exercise_level_cat" => "ocio 15 2 km / h"],
    ["id" => "47", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, 16-19,2 km / h, leisure, light effort", "idMET" => "1020", "MET" => "6.80", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, 16-19,2 km / h, ocio, lento, esfuerzo ligero", "description_es" => "ciclismo, 16-19,2 km / h, ocio, lento, esfuerzo ligero", "description_val" => "ciclismo, 16-19,2 km / h, ocio, lento, esfuerzo ligero", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "16-19 2 km / h ocio lento esfuerzo ligero", "exercise_level_es" => "16-19 2 km / h ocio lento esfuerzo ligero", "exercise_level_en" => "16-19 2 km / h leisure light effort", "exercise_level_cat" => "16-19 2 km / h ocio lento esfuerzo ligero"],
    ["id" => "48", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, 19-22,4 km / h, leisure, moderate effort", "idMET" => "1030", "MET" => "8.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, 19-22,4 km / h, ocio, esfuerzo moderado", "description_es" => "ciclismo, 19-22,4 km / h, ocio, esfuerzo moderado", "description_val" => "ciclismo, 19-22,4 km / h, ocio, esfuerzo moderado", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "19-22 4 km / h ocio esfuerzo moderado", "exercise_level_es" => "19-22 4 km / h ocio esfuerzo moderado", "exercise_level_en" => "19-22 4 km / h leisure moderate effort", "exercise_level_cat" => "19-22 4 km / h ocio esfuerzo moderado"],
    ["id" => "49", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, 22,5-25,6 km / h, carreras u ocio, rapid vigorous effort", "idMET" => "1040", "MET" => "10.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, 22,5-25,6 km / h, carreras u ocio, esfuerzo rápido y vigoroso", "description_es" => "ciclismo, 22,5-25,6 km / h, carreras u ocio, esfuerzo rápido y vigoroso", "description_val" => "ciclismo, 22,5-25,6 km / h, carreras u ocio, esfuerzo rápido y vigoroso", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "22 44706 6 km / h carreras u ocio esfuerzo rápido y vigoroso", "exercise_level_es" => "22 44706 6 km / h carreras u ocio esfuerzo rápido y vigoroso", "exercise_level_en" => "22 44706 6 km / h carreras u", "exercise_level_cat" => "22 44706 6 km / h carreras u ocio esfuerzo rápido y vigoroso"],
    ["id" => "50", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, 25-31 km / h, carreras / sin drafting o > 31 km / h drafting, muy rápido, carreras en general", "idMET" => "1050", "MET" => "12.00", "duration" => "30", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, 25-31 km / h, carreras / sin drafting o > 31 km / h drafting, muy rápido, carreras en general", "description_es" => "ciclismo, 25-31 km / h, carreras / sin drafting o > 31 km / h drafting, muy rápido, carreras en general", "description_val" => "ciclismo, 25-31 km / h, carreras / sin drafting o > 31 km / h drafting, muy rápido, carreras en general", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "25-31 km / h carreras / sin drafting o > 31 km / h drafting muy rápido carreras en general", "exercise_level_es" => "25-31 km / h carreras / sin drafting o > 31 km / h drafting muy rápido carreras en general", "exercise_level_en" => "25-31 km / h carreras / sin drafting o >", "exercise_level_cat" => "25-31 km / h carreras / sin drafting o > 31 km / h drafting muy rápido carreras en general"],
    ["id" => "51", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 30-50 watts, very light to light effort", "idMET" => "2011", "MET" => "3.50", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 30-50 vatios, esfuerzo muy ligero a ligero", "description_es" => "ciclismo, estacionario, 30-50 vatios, esfuerzo muy ligero a ligero", "description_val" => "ciclismo, estacionario, 30-50 vatios, esfuerzo muy ligero a ligero", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 30-50 vatios esfuerzo muy ligero a ligero", "exercise_level_es" => "estacionario 30-50 vatios esfuerzo muy ligero a ligero", "exercise_level_en" => "Stationary 30-50 watts very light to", "exercise_level_cat" => "estacionario 30-50 vatios esfuerzo muy ligero a ligero"],
    ["id" => "52", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 90-100 watts, moderate to rigorous", "idMET" => "2012", "MET" => "6.80", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 90-100 vatios, esfuerzo moderado a vigoroso", "description_es" => "ciclismo, estacionario, 90-100 vatios, esfuerzo moderado a vigoroso", "description_val" => "ciclismo, estacionario, 90-100 vatios, esfuerzo moderado a vigoroso", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 90-100 vatios esfuerzo moderado a vigoroso", "exercise_level_es" => "estacionario 90-100 vatios esfuerzo moderado a vigoroso", "exercise_level_en" => "Stationary 90-100 watts moderate to rigorous", "exercise_level_cat" => "estacionario 90-100 vatios esfuerzo moderado a vigoroso"],
    ["id" => "53", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 101-160 watts, vigorous effort", "idMET" => "2013", "MET" => "8.80", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 101-160 vatios, esfuerzo vigoroso", "description_es" => "ciclismo, estacionario, 101-160 vatios, esfuerzo vigoroso", "description_val" => "ciclismo, estacionario, 101-160 vatios, esfuerzo vigoroso", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 101-160 vatios esfuerzo vigoroso", "exercise_level_es" => "estacionario 101-160 vatios esfuerzo vigoroso", "exercise_level_en" => "Stationary 101-160 watts vigorous effort", "exercise_level_cat" => "estacionario 101-160 vatios esfuerzo vigoroso"],
    ["id" => "54", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 161-200 watts, vigorous effort", "idMET" => "2014", "MET" => "11.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 161-200 vatios, esfuerzo vigoroso", "description_es" => "ciclismo, estacionario, 161-200 vatios, esfuerzo vigoroso", "description_val" => "ciclismo, estacionario, 161-200 vatios, esfuerzo vigoroso", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 161-200 vatios esfuerzo vigoroso", "exercise_level_es" => "estacionario 161-200 vatios esfuerzo vigoroso", "exercise_level_en" => "Stationary 161-200 watts vigorous effort", "exercise_level_cat" => "estacionario 161-200 vatios esfuerzo vigoroso"],
    ["id" => "55", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 201-270 watts, very vigorous effort", "idMET" => "2015", "MET" => "14.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 201-270 vatios, esfuerzo muy vigoroso", "description_es" => "ciclismo, estacionario, 201-270 vatios, esfuerzo muy vigoroso", "description_val" => "ciclismo, estacionario, 201-270 vatios, esfuerzo muy vigoroso", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 201-270 vatios esfuerzo muy vigoroso", "exercise_level_es" => "estacionario 201-270 vatios esfuerzo muy vigoroso", "exercise_level_en" => "Stationary 201-270 watts very vigorous effort", "exercise_level_cat" => "estacionario 201-270 vatios esfuerzo muy vigoroso"],
    ["id" => "56", "video_yt_name" => "", "routine_en" => "Cycling", "description_en" => "cycling, Stationary, 51-89 watts, light to moderate effort", "idMET" => "2017", "MET" => "4.80", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Ciclismo", "routine_cat" => "Ciclisme", "routine_val" => "Ciclisme", "description_cat" => "ciclismo, estacionario, 51-89 vatios, esfuerzo ligero a moderado", "description_es" => "ciclismo, estacionario, 51-89 vatios, esfuerzo ligero a moderado", "description_val" => "ciclismo, estacionario, 51-89 vatios, esfuerzo ligero a moderado", "exercise_type_val" => "ciclismo", "exercise_type_es" => "ciclismo", "exercise_type_en" => "cycling", "exercise_type_cat" => "ciclismo", "exercise_level_val" => "estacionario 51-89 vatios esfuerzo ligero a moderado", "exercise_level_es" => "estacionario 51-89 vatios esfuerzo ligero a moderado", "exercise_level_en" => "Stationary 51-89 watts light to moderate", "exercise_level_cat" => "estacionario 51-89 vatios esfuerzo ligero a moderado"],
    ["id" => "57", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "", "idMET" => "12010", "MET" => "6.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "description_es" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "description_val" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_type_val" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_type_es" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_type_en" => "run", "exercise_type_cat" => "combinacion de trote / caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_level_val" => "/ caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_level_es" => "/ caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)", "exercise_level_en" => "", "exercise_level_cat" => "/ caminata (componente de trote de menos de 10 minutos) (Codigo Taylor 180)"],
    ["id" => "58", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 6,44 km / h (9,32 min / km)", "idMET" => "12029", "MET" => "6.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 6,44 km / h (9,32 min / km)", "description_es" => "correr; 6,44 km / h (9,32 min / km)", "description_val" => "correr; 6,44 km / h (9,32 min / km)", "exercise_type_val" => "correr; 6", "exercise_type_es" => "correr; 6", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 6", "exercise_level_val" => "44 km / h (9 32 min / km)", "exercise_level_es" => "44 km / h (9 32 min / km)", "exercise_level_en" => "6 44 km / h (9 32 min / km)", "exercise_level_cat" => "44 km / h (9 32 min / km)"],
    ["id" => "59", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 8,05 km / h (7,45 min / km)", "idMET" => "12030", "MET" => "8.30", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 8,05 km / h (7,45 min / km)", "description_es" => "correr; 8,05 km / h (7,45 min / km)", "description_val" => "correr; 8,05 km / h (7,45 min / km)", "exercise_type_val" => "correr; 8", "exercise_type_es" => "correr; 8", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 8", "exercise_level_val" => "05 km / h (7 45 min / km)", "exercise_level_es" => "05 km / h (7 45 min / km)", "exercise_level_en" => "8 5 km / h (7 45 min / km)", "exercise_level_cat" => "05 km / h (7 45 min / km)"],
    ["id" => "60", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 8,37 km / h (7,17 min / km)", "idMET" => "12040", "MET" => "9.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 8,37 km / h (7,17 min / km)", "description_es" => "correr; 8,37 km / h (7,17 min / km)", "description_val" => "correr; 8,37 km / h (7,17 min / km)", "exercise_type_val" => "correr; 8", "exercise_type_es" => "correr; 8", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 8", "exercise_level_val" => "37 km / h (7 17 min / km)", "exercise_level_es" => "37 km / h (7 17 min / km)", "exercise_level_en" => "8 37 km / h (7 17 min / km)", "exercise_level_cat" => "37 km / h (7 17 min / km)"],
    ["id" => "61", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 9,66 km / h (6,21 min / km)", "idMET" => "12050", "MET" => "9.80", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 9,66 km / h (6,21 min / km)", "description_es" => "correr; 9,66 km / h (6,21 min / km)", "description_val" => "correr; 9,66 km / h (6,21 min / km)", "exercise_type_val" => "correr; 9", "exercise_type_es" => "correr; 9", "exercise_type_en" => "Fast", "exercise_type_cat" => "correr; 9", "exercise_level_val" => "66 km / h (6 21 min / km)", "exercise_level_es" => "66 km / h (6 21 min / km)", "exercise_level_en" => "9 66 km / h (6 21 min / km)", "exercise_level_cat" => "66 km / h (6 21 min / km)"],
    ["id" => "62", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 10,78 km / h (5,57 min / km)", "idMET" => "12060", "MET" => "10.50", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 10,78 km / h (5,57 min / km)", "description_es" => "correr; 10,78 km / h (5,57 min / km)", "description_val" => "correr; 10,78 km / h (5,57 min / km)", "exercise_type_val" => "correr; 10", "exercise_type_es" => "correr; 10", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 10", "exercise_level_val" => "78 km / h (5 57 min / km)", "exercise_level_es" => "78 km / h (5 57 min / km)", "exercise_level_en" => "10 78 km / h (5 57 min / km)", "exercise_level_cat" => "78 km / h (5 57 min / km)"],
    ["id" => "63", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 11,27 km / h (5,32 min / km)", "idMET" => "12070", "MET" => "11.00", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 11,27 km / h (5,32 min / km)", "description_es" => "correr; 11,27 km / h (5,32 min / km)", "description_val" => "correr; 11,27 km / h (5,32 min / km)", "exercise_type_val" => "correr; 11", "exercise_type_es" => "correr; 11", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 11", "exercise_level_val" => "27 km / h (5 32 min / km)", "exercise_level_es" => "27 km / h (5 32 min / km)", "exercise_level_en" => "11 27 km / h (5 32 min / km)", "exercise_level_cat" => "27 km / h (5 32 min / km)"],
    ["id" => "64", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 12,07 km / h (4,97 min / km)", "idMET" => "12080", "MET" => "11.50", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 12,07 km / h (4,97 min / km)", "description_es" => "correr; 12,07 km / h (4,97 min / km)", "description_val" => "correr; 12,07 km / h (4,97 min / km)", "exercise_type_val" => "correr; 12", "exercise_type_es" => "correr; 12", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 12", "exercise_level_val" => "07 km / h (4 97 min / km)", "exercise_level_es" => "07 km / h (4 97 min / km)", "exercise_level_en" => "12 7 km / h (4 97 min / km)", "exercise_level_cat" => "07 km / h (4 97 min / km)"],
    ["id" => "65", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 12,87 km / h (4,66 min / km)", "idMET" => "12090", "MET" => "11.80", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 12,87 km / h (4,66 min / km)", "description_es" => "correr; 12,87 km / h (4,66 min / km)", "description_val" => "correr; 12,87 km / h (4,66 min / km)", "exercise_type_val" => "correr; 12", "exercise_type_es" => "correr; 12", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 12", "exercise_level_val" => "87 km / h (4 66 min / km)", "exercise_level_es" => "87 km / h (4 66 min / km)", "exercise_level_en" => "12 87 km / h (4 66 min / km)", "exercise_level_cat" => "87 km / h (4 66 min / km)"],
    ["id" => "66", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 13,84 km / h (4,33 min / km)", "idMET" => "12100", "MET" => "12.30", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 13,84 km / h (4,33 min / km)", "description_es" => "correr; 13,84 km / h (4,33 min / km)", "description_val" => "correr; 13,84 km / h (4,33 min / km)", "exercise_type_val" => "correr; 13", "exercise_type_es" => "correr; 13", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 13", "exercise_level_val" => "84 km / h (4 33 min / km)", "exercise_level_es" => "84 km / h (4 33 min / km)", "exercise_level_en" => "13 84 km / h (4 33 min / km)", "exercise_level_cat" => "84 km / h (4 33 min / km)"],
    ["id" => "67", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 14,48 km / h (4,14 min / km)", "idMET" => "12110", "MET" => "12.80", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 14,48 km / h (4,14 min / km)", "description_es" => "correr; 14,48 km / h (4,14 min / km)", "description_val" => "correr; 14,48 km / h (4,14 min / km)", "exercise_type_val" => "correr; 14", "exercise_type_es" => "correr; 14", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 14", "exercise_level_val" => "48 km / h (4 14 min / km)", "exercise_level_es" => "48 km / h (4 14 min / km)", "exercise_level_en" => "14 48 km / h (4 14 min / km)", "exercise_level_cat" => "48 km / h (4 14 min / km)"],
    ["id" => "68", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 16,09 km / h (3,73 min / km)", "idMET" => "12120", "MET" => "14.50", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 16,09 km / h (3,73 min / km)", "description_es" => "correr; 16,09 km / h (3,73 min / km)", "description_val" => "correr; 16,09 km / h (3,73 min / km)", "exercise_type_val" => "correr; 16", "exercise_type_es" => "correr; 16", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 16", "exercise_level_val" => "09 km / h (3 73 min / km)", "exercise_level_es" => "09 km / h (3 73 min / km)", "exercise_level_en" => "16 9 km / h (3 73 min / km)", "exercise_level_cat" => "09 km / h (3 73 min / km)"],
    ["id" => "69", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 17,70 km / h (3,39 min / km)", "idMET" => "12130", "MET" => "16.00", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 17,70 km / h (3,39 min / km)", "description_es" => "correr; 17,70 km / h (3,39 min / km)", "description_val" => "correr; 17,70 km / h (3,39 min / km)", "exercise_type_val" => "correr; 17", "exercise_type_es" => "correr; 17", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 17", "exercise_level_val" => "70 km / h (3 39 min / km)", "exercise_level_es" => "70 km / h (3 39 min / km)", "exercise_level_en" => "17 70 km / h (3 39 min / km)", "exercise_level_cat" => "70 km / h (3 39 min / km)"],
    ["id" => "70", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 19,31 km / h (3,11 min / km)", "idMET" => "12132", "MET" => "19.00", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 19,31 km / h (3,11 min / km)", "description_es" => "correr; 19,31 km / h (3,11 min / km)", "description_val" => "correr; 19,31 km / h (3,11 min / km)", "exercise_type_val" => "correr; 19", "exercise_type_es" => "correr; 19", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 19", "exercise_level_val" => "31 km / h (3 11 min / km)", "exercise_level_es" => "31 km / h (3 11 min / km)", "exercise_level_en" => "19 31 km / h (3 11 min / km)", "exercise_level_cat" => "31 km / h (3 11 min / km)"],
    ["id" => "71", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 20,92 km / h (2,87 min / km)", "idMET" => "12134", "MET" => "19.80", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 20,92 km / h (2,87 min / km)", "description_es" => "correr; 20,92 km / h (2,87 min / km)", "description_val" => "correr; 20,92 km / h (2,87 min / km)", "exercise_type_val" => "correr; 20", "exercise_type_es" => "correr; 20", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 20", "exercise_level_val" => "92 km / h (2 87 min / km)", "exercise_level_es" => "92 km / h (2 87 min / km)", "exercise_level_en" => "20 92 km / h (2 87 min / km)", "exercise_level_cat" => "92 km / h (2 87 min / km)"],
    ["id" => "72", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run; 22,53 km / h (2,66 min / km)", "idMET" => "12135", "MET" => "23.00", "duration" => "15", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr; 22,53 km / h (2,66 min / km)", "description_es" => "correr; 22,53 km / h (2,66 min / km)", "description_val" => "correr; 22,53 km / h (2,66 min / km)", "exercise_type_val" => "correr; 22", "exercise_type_es" => "correr; 22", "exercise_type_en" => "run", "exercise_type_cat" => "correr; 22", "exercise_level_val" => "53 km / h (2 66 min / km)", "exercise_level_es" => "53 km / h (2 66 min / km)", "exercise_level_en" => "22 53 km / h (2 66 min / km)", "exercise_level_cat" => "53 km / h (2 66 min / km)"],
    ["id" => "73", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run, cross country", "idMET" => "12140", "MET" => "9.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr, campo a través", "description_es" => "correr, campo a través", "description_val" => "correr, campo a través", "exercise_type_val" => "correr", "exercise_type_es" => "correr", "exercise_type_en" => "run", "exercise_type_cat" => "correr", "exercise_level_val" => "campo a través", "exercise_level_es" => "campo a través", "exercise_level_en" => "cross country", "exercise_level_cat" => "campo a través"],
    ["id" => "74", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "run upstairs", "idMET" => "12170", "MET" => "15.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "correr escaleras arriba", "description_es" => "correr escaleras arriba", "description_val" => "correr escaleras arriba", "exercise_type_val" => "correr escaleras arriba", "exercise_type_es" => "correr escaleras arriba", "exercise_type_en" => "run", "exercise_type_cat" => "correr escaleras arriba", "exercise_level_val" => "", "exercise_level_es" => "", "exercise_level_en" => "upstairs", "exercise_level_cat" => ""],
    ["id" => "75", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "walking race", "idMET" => "17110", "MET" => "6.50", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "carrera caminando", "description_es" => "carrera caminando", "description_val" => "carrera caminando", "exercise_type_val" => "carrera caminando", "exercise_type_es" => "carrera caminando", "exercise_type_en" => "", "exercise_type_cat" => "carrera caminando", "exercise_level_val" => "", "exercise_level_es" => "", "exercise_level_en" => "race", "exercise_level_cat" => ""],
    ["id" => "76", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "climb stairs, slow pace", "idMET" => "17133", "MET" => "4.00", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "subir escaleras, ritmo lento", "description_es" => "subir escaleras, ritmo lento", "description_val" => "subir escaleras, ritmo lento", "exercise_type_val" => "subir escaleras", "exercise_type_es" => "subir escaleras", "exercise_type_en" => "climbing", "exercise_type_cat" => "subir escaleras", "exercise_level_val" => "ritmo lento", "exercise_level_es" => "ritmo lento", "exercise_level_en" => "stairs slow pace", "exercise_level_cat" => "ritmo lento"],
    ["id" => "77", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "climbing stairs, fast pace", "idMET" => "17134", "MET" => "8.80", "duration" => "10", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "subir escaleras, ritmo rápido", "description_es" => "subir escaleras, ritmo rápido", "description_val" => "subir escaleras, ritmo rápido", "exercise_type_val" => "subir escaleras", "exercise_type_es" => "subir escaleras", "exercise_type_en" => "Elliptical", "exercise_type_cat" => "subir escaleras", "exercise_level_val" => "ritmo rápido", "exercise_level_es" => "ritmo rápido", "exercise_level_en" => "stairs fast pace", "exercise_level_cat" => "ritmo rápido"],
    ["id" => "78", "video_yt_name" => "", "routine_en" => "walk / run", "description_en" => "Fast March", "idMET" => "17090", "MET" => "8.00", "duration" => "20", "youtube" => "", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Andar / correr", "routine_cat" => "caminar / correr", "routine_val" => "caminar / correr", "description_cat" => "marcha rápida", "description_es" => "marcha rápida", "description_val" => "marcha rápida", "exercise_type_val" => "marcha rápida", "exercise_type_es" => "marcha rápida", "exercise_type_en" => "walking", "exercise_type_cat" => "marcha rápida", "exercise_level_val" => "", "exercise_level_es" => "", "exercise_level_en" => "March", "exercise_level_cat" => ""],
    ["id" => "79", "video_yt_name" => "1.BÁSICO", "routine_en" => "Session", "description_en" => "Functional Basic 4", "idMET" => "2022", "MET" => "3.80", "duration" => "29", "youtube" => "https://youtube.com/embed/GaJuadIUOP0", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional básico 4", "description_es" => "Funcional básico 4", "description_val" => "Funcional básico 4", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "básico 4", "exercise_level_es" => "básico 4", "exercise_level_en" => "Basic 4", "exercise_level_cat" => "básico 4"],
    ["id" => "80", "video_yt_name" => "1.BÁSICO", "routine_en" => "Session", "description_en" => "Functional Medium 6", "idMET" => "2022", "MET" => "3.80", "duration" => "29", "youtube" => "https://youtube.com/embed/GaJuadIUOP0", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional medio 6", "description_es" => "Funcional medio 6", "description_val" => "Funcional medio 6", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "medio 6", "exercise_level_es" => "medio 6", "exercise_level_en" => "Medium 6", "exercise_level_cat" => "medio 6"],
    ["id" => "81", "video_yt_name" => "1.MEDIO", "routine_en" => "Session", "description_en" => "Functional Medium 3", "idMET" => "2022", "MET" => "3.80", "duration" => "28", "youtube" => "https://youtube.com/embed/OnoYZhyCdCg", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional medio 3", "description_es" => "Funcional medio 3", "description_val" => "Funcional medio 3", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "medio 3", "exercise_level_es" => "medio 3", "exercise_level_en" => "Medium 3", "exercise_level_cat" => "medio 3"],
    ["id" => "82", "video_yt_name" => "Básico 2", "routine_en" => "Session", "description_en" => "Functional Basic 5", "idMET" => "2024", "MET" => "2.80", "duration" => "29", "youtube" => "https://youtube.com/embed/Tjn6siseEbU", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional básico 5", "description_es" => "Funcional básico 5", "description_val" => "Funcional básico 5", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "básico 5", "exercise_level_es" => "básico 5", "exercise_level_en" => "Basic 5", "exercise_level_cat" => "básico 5"],
    ["id" => "83", "video_yt_name" => "Básico 3", "routine_en" => "Session", "description_en" => "Functional Basic 3", "idMET" => "2024", "MET" => "2.80", "duration" => "21", "youtube" => "https://youtube.com/embed/18qcq4iBajo", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional básico 3", "description_es" => "Funcional básico 3", "description_val" => "Funcional básico 3", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "básico 3", "exercise_level_es" => "básico 3", "exercise_level_en" => "Basic 3", "exercise_level_cat" => "básico 3"],
    ["id" => "84", "video_yt_name" => "HiIT intermedio", "routine_en" => "Session", "description_en" => "Functional Advanced 3", "idMET" => "2146", "MET" => "6.00", "duration" => "11", "youtube" => "https://youtube.com/embed/sz13NFnqJYA", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional avanzado 3", "description_es" => "Funcional avanzado 3", "description_val" => "Funcional avanzado 3", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "avanzado 3", "exercise_level_es" => "avanzado 3", "exercise_level_en" => "Advanced 3", "exercise_level_cat" => "avanzado 3"],
    ["id" => "85", "video_yt_name" => "HiIT intermedio", "routine_en" => "Session", "description_en" => "Functional Medium 4", "idMET" => "2146", "MET" => "6.00", "duration" => "11", "youtube" => "https://youtube.com/embed/sz13NFnqJYA", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional medio 4", "description_es" => "Funcional medio 4", "description_val" => "Funcional medio 4", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "medio 4", "exercise_level_es" => "medio 4", "exercise_level_en" => "Medium 4", "exercise_level_cat" => "medio 4"],
    ["id" => "86", "video_yt_name" => "HiIT intermedio 2", "routine_en" => "Session", "description_en" => "Functional Advanced 4", "idMET" => "2146", "MET" => "6.00", "duration" => "12", "youtube" => "https://youtube.com/embed/xPOlLOG-25o", "created_at" => "2022-09-16 00:00:00", "updated_at" => "2022-09-16 00:00:00", "routine_es" => "Sesion", "routine_cat" => "Sessio", "routine_val" => "Sessio", "description_cat" => "Funcional avanzado 4", "description_es" => "Funcional avanzado 4", "description_val" => "Funcional avanzado 4", "exercise_type_val" => "Funcional", "exercise_type_es" => "Funcional", "exercise_type_en" => "Functional", "exercise_type_cat" => "Funcional", "exercise_level_val" => "avanzado 4", "exercise_level_es" => "avanzado 4", "exercise_level_en" => "Advanced 4", "exercise_level_cat" => "avanzado 4"]



];
Route::prefix('icon')->group(function () {  // word: "icons" - not working as part of adress
    Route::get('/coreui-icons', function () {
        return view('dashboard.icons.coreui-icons');
    });
    Route::get('/flags', function () {
        return view('dashboard.icons.flags');
    });
    Route::get('/brands', function () {
        return view('dashboard.icons.brands');
    });
});
Route::get('/colors', function () {
    return view('dashboard.colors');
});
Route::get('/typography', function () {
    return view('dashboard.typography');
});
Route::get('/charts', function () {
    return view('dashboard.charts');
});
Route::get('/widgets', function () {
    return view('dashboard.widgets');
});
Route::get('/404', function () {
    return view('dashboard.404');
});
Route::get('/500', function () {
    return view('dashboard.500');
});
Route::prefix('base')->group(function () {
    Route::get('/breadcrumb', function () {
        return view('dashboard.base.breadcrumb');
    });
    Route::get('/cards', function () {
        return view('dashboard.base.cards');
    });
    Route::get('/carousel', function () {
        return view('dashboard.base.carousel');
    });
    Route::get('/collapse', function () {
        return view('dashboard.base.collapse');
    });

    Route::get('/forms', function () {
        return view('dashboard.base.forms');
    });
    Route::get('/jumbotron', function () {
        return view('dashboard.base.jumbotron');
    });
    Route::get('/list-group', function () {
        return view('dashboard.base.list-group');
    });
    Route::get('/navs', function () {
        return view('dashboard.base.navs');
    });

    Route::get('/pagination', function () {
        return view('dashboard.base.pagination');
    });
    Route::get('/popovers', function () {
        return view('dashboard.base.popovers');
    });
    Route::get('/progress', function () {
        return view('dashboard.base.progress');
    });
    Route::get('/scrollspy', function () {
        return view('dashboard.base.scrollspy');
    });

    Route::get('/switches', function () {
        return view('dashboard.base.switches');
    });
    Route::get('/tables', function () {
        return view('dashboard.base.tables');
    });
    Route::get('/tabs', function () {
        return view('dashboard.base.tabs');
    });
    Route::get('/tooltips', function () {
        return view('dashboard.base.tooltips');
    });

    Route::get('/', function () {
        return view('dashboard.homepage');
    });

    Route::group(['middleware' => ['role:user']], function () {
    });
    Route::prefix('buttons')->group(function () {
        Route::get('/buttons', function () {
            return view('dashboard.buttons.buttons');
        });
        Route::get('/button-group', function () {
            return view('dashboard.buttons.button-group');
        });
        Route::get('/dropdowns', function () {
            return view('dashboard.buttons.dropdowns');
        });
        Route::get('/brand-buttons', function () {
            return view('dashboard.buttons.brand-buttons');
        });
    });

    Route::prefix('notifications')->group(function () {
        Route::get('/alerts', function () {
            return view('dashboard.notifications.alerts');
        });
        Route::get('/badge', function () {
            return view('dashboard.notifications.badge');
        });
        Route::get('/modals', function () {
            return view('dashboard.notifications.modals');
        });
    });
    Route::resource('notes', 'NotesController');
});
Auth::routes();

Route::resource('resource/{table}/resource', 'ResourceController')->names([
    'index'     => 'resource.index',
    'create'    => 'resource.create',
    'store'     => 'resource.store',
    'show'      => 'resource.show',
    'edit'      => 'resource.edit',
    'update'    => 'resource.update',
    'destroy'   => 'resource.destroy'
]);

Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('bread',  'BreadController');   //create BREAD (resource)
    Route::resource('users',        'UsersController')->except(['create', 'store']);
    Route::resource('roles',        'RolesController');
    Route::resource('mail',        'MailController');
    Route::get('prepareSend/{id}',        'MailController@prepareSend')->name('prepareSend');
    Route::post('mailSend/{id}',        'MailController@send')->name('mailSend');
    Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
    Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');
    Route::prefix('menu/element')->group(function () {
        Route::get('/',             'MenuElementController@index')->name('menu.index');
        Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
        Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
        Route::get('/create',       'MenuElementController@create')->name('menu.create');
        Route::post('/store',       'MenuElementController@store')->name('menu.store');
        Route::get('/get-parents',  'MenuElementController@getParents');
        Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
        Route::post('/update',      'MenuElementController@update')->name('menu.update');
        Route::get('/show',         'MenuElementController@show')->name('menu.show');
        Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
    });
    Route::prefix('menu/menu')->group(function () {
        Route::get('/',         'MenuController@index')->name('menu.menu.index');
        Route::get('/create',   'MenuController@create')->name('menu.menu.create');
        Route::post('/store',   'MenuController@store')->name('menu.menu.store');
        Route::get('/edit',     'MenuController@edit')->name('menu.menu.edit');
        Route::post('/update',  'MenuController@update')->name('menu.menu.update');
        Route::get('/delete',   'MenuController@delete')->name('menu.menu.delete');
    });
    Route::prefix('media')->group(function () {
        Route::get('/',                 'MediaController@index')->name('media.folder.index');
        Route::get('/folder/store',     'MediaController@folderAdd')->name('media.folder.add');
        Route::post('/folder/update',   'MediaController@folderUpdate')->name('media.folder.update');
        Route::get('/folder',           'MediaController@folder')->name('media.folder');
        Route::post('/folder/move',     'MediaController@folderMove')->name('media.folder.move');
        Route::post('/folder/delete',   'MediaController@folderDelete')->name('media.folder.delete');;

        Route::post('/file/store',      'MediaController@fileAdd')->name('media.file.add');
        Route::get('/file',             'MediaController@file');
        Route::post('/file/delete',     'MediaController@fileDelete')->name('media.file.delete');
        Route::post('/file/update',     'MediaController@fileUpdate')->name('media.file.update');
        Route::post('/file/move',       'MediaController@fileMove')->name('media.file.move');
        Route::post('/file/cropp',      'MediaController@cropp');
        Route::get('/file/copy',        'MediaController@fileCopy')->name('media.file.copy');
    });
});*/